### ISSUE TITLE
Fatal PHP error on fresh Woocommerce installation.

### ISSUE THREAD

**Issue by opicron** [gdarko/digital-license-manager#46]
I created on a fresh empty site a license and trying to view the license through woocommerce > account > view license.

The following fatal error occurs.

Note that this is an manually created serial imported from License Manager for Woocommerce.

```
PHP FatalUncaught Error: Call to a member function get_view_order_url() on nullStack trace:#0 /wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include()#1 /wp-content/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template()#2 /wp-content/plugins/digital-license-manager/includes/Integrations/WooCommerce/MyAccount.php(294): wc_get_template_html()#3 /wp-includes/class-wp-hook.php(324): IdeoLogix\DigitalLicenseManager\Integrations\WooCommerce\MyAccount->addSingleLicenseContent()#4 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#5 /home/991455.clo in /wp-content/plugins/digital-license-manager/templates/woocommerce/dlm/my-account/licenses/single.php on line 104Plugin: [Digital License Manager](https://codeverve.com/product/digital-license-manager-pro/)
File: [/wp-content/plugins/digital-license-manager/templates/woocommerce/dlm/my-account/licenses/single.php](https://thawk.nl/wp-admin/plugin-editor.php?file=digital-license-manager%2Ftemplates%2Fwoocommerce%2Fdlm%2Fmy-account%2Flicenses%2Fsingle.php&plugin=digital-license-manager%2Fdigital-license-manager.php)
Line: 104
```

**Comment by gdarko** [comment]
Closed in https://github.com/gdarko/digital-license-manager/commit/a32a4031a1743bdfbb61b82507851e72936f871f
