### ISSUE TITLE
PHP fatal error on 1.5.1 pro / 1.7.1

### ISSUE THREAD

**Issue by opicron** [gdarko/digital-license-manager#51]
I noticed an PHP fatal error when running WP CLI on command line. This happens both on 1.7.1 and 1.5.1 pro.

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function IdeoLogix\DigitalLicenseManager\Abstracts\AbstractTool::__construct(), 0 passed in /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Integrations/WooCommerce/Controller.php on line 280 and exactly 1 expected in /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Abstracts/AbstractTool.php:58
Stack trace:
#0 /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Integrations/WooCommerce/Controller.php(280): IdeoLogix\DigitalLicenseManager\Abstracts\AbstractTool->__construct()
#1 /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-includes/class-wp-hook.php(324): IdeoLogix\DigitalLicenseManager\Integrations\WooCommerce\Controller->registerCommands()
#2 /home/991455.c in /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Abstracts/AbstractTool.php on line 58
Fatal error: Uncaught ArgumentCountError: Too few arguments to function IdeoLogix\DigitalLicenseManager\Abstracts\AbstractTool::__construct(), 0 passed in /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Integrations/WooCommerce/Controller.php on line 280 and exactly 1 expected in /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Abstracts/AbstractTool.php:58
Stack trace:
#0 /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Integrations/WooCommerce/Controller.php(280): IdeoLogix\DigitalLicenseManager\Abstracts\AbstractTool->__construct()
#1 /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-includes/class-wp-hook.php(324): IdeoLogix\DigitalLicenseManager\Integrations\WooCommerce\Controller->registerCommands()
#2 /home/991455.c in /home/991455.cloudwaysapps.com/juseyhuctm/public_html/wp-content/plugins/digital-license-manager-pro/vendor/gdarko/digital-license-manager/includes/Abstracts/AbstractTool.php on line 58
`

**Comment by opicron** [comment]
@gdarko Happy Newyear! Any chance you could take a look at this?

**Comment by opicron** [comment]
For others who have this issue, I created an wp-cli.yml file with:

`skip-plugins:
  - digital-license-manager-pro`

Which prevents the plugin from loading so my cli scripts continue to run.

**Comment by opicron** [comment]
Thank you for your quick response. I confirm the issue is fixed with the latest release.
